In [4]:
import matplotlib.pyplot as plt
import pandas as pd
import numpy as np

import warnings
warnings.filterwarnings('ignore')
warnings.simplefilter('always', FutureWarning)

In [5]:
df =pd.read_csv('movies1.csv')
df.head(2)

movieId             title                                       genres
0        1  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy
1        2    Jumanji (1995)                   Adventure|Children|Fantasy

In [6]:
del df['movieId']

In [7]:
df.head(1)

title                                       genres
0  Toy Story (1995)  Adventure|Animation|Children|Comedy|Fantasy

In [8]:
df.info()

<class 'pandas.core.frame.DataFrame'>
RangeIndex: 9742 entries, 0 to 9741
Data columns (total 2 columns):
 #   Column  Non-Null Count  Dtype 
---  ------  --------------  ----- 
 0   title   9742 non-null   object
 1   genres  9742 non-null   object
dtypes: object(2)
memory usage: 152.3+ KB


In [9]:
df.dtypes

title     object
genres    object
dtype: object

In [10]:
df.describe()

title genres
count                       9742   9742
unique                      9737    951
top     War of the Worlds (2005)  Drama
freq                           2   1053

In [11]:
df['title'].value_counts()

War of the Worlds (2005)                                             2
Saturn 3 (1980)                                                      2
Emma (1996)                                                          2
Eros (2004)                                                          2
Confessions of a Dangerous Mind (2002)                               2
                                                                    ..
Christmas Vacation (National Lampoon's Christmas Vacation) (1989)    1
Herbie Rides Again (1974)                                            1
Slap Shot (1977)                                                     1
Open Water 2: Adrift (2006)                                          1
Elmer Gantry (1960)                                                  1
Name: title, Length: 9737, dtype: int64

In [12]:
df['genres'].value_counts()

Drama                                        1053
Comedy                                        946
Comedy|Drama                                  435
Comedy|Romance                                363
Drama|Romance                                 349
                                             ... 
Adventure|Children|Comedy|Fantasy|Mystery       1
Crime|Drama|Film-Noir|Mystery                   1
Crime|Drama|Thriller|War                        1
Children|Drama|Fantasy|Mystery                  1
Adventure|Animation|Children|Western            1
Name: genres, Length: 951, dtype: int64

In [16]:
title_dummy = pd.get_dummies(df['title'])
genres_dummy = pd.get_dummies(df['genres'])

In [17]:
df_dummy_set = pd.concat([df,
    title_dummy , genres_dummy
], axis=1)

In [18]:
del df_dummy_set['title']
del df_dummy_set['genres']

In [19]:
df_dummy_set

'71 (2014)  'Hellboy': The Seeds of Creation (2004)  \
0              0                                        0   
1              0                                        0   
2              0                                        0   
3              0                                        0   
4              0                                        0   
...          ...                                      ...   
9737           0                                        0   
9738           0                                        0   
9739           0                                        0   
9740           0                                        0   
9741           0                                        0   

      'Round Midnight (1986)  'Salem's Lot (2004)  'Til There Was You (1997)  \
0                          0                    0                          0   
1                          0                    0                          0   
2                          0                    0                          0   
3                          0                    0                          0   
4                          0                    0                          0   
...                      ...                  ...                        ...   
9737                       0                    0                          0   
9738                       0                    0                          0   
9739                       0                    0                          0   
9740                       0                    0                          0   
9741                       0                    0                          0   

      'Tis the Season for Love (2015)  'burbs, The (1989)  \
0                                   0                   0   
1                                   0                   0   
2                                   0                   0   
3                                   0                   0   
4                                   0                   0   
...                               ...                 ...   
9737                                0                   0   
9738                                0                   0   
9739                                0                   0   
9740                                0                   0   
9741                                0                   0   

      'night Mother (1986)  (500) Days of Summer (2009)  \
0                        0                            0   
1                        0                            0   
2                        0                            0   
3                        0                            0   
4                        0                            0   
...                    ...                          ...   
9737                     0                            0   
9738                     0                            0   
9739                     0                            0   
9740                     0                            0   
9741                     0                            0   

      *batteries not included (1987)  ...  Romance|Thriller  Romance|War  \
0                                  0  ...                 0            0   
1                                  0  ...                 0            0   
2                                  0  ...                 0            0   
3                                  0  ...                 0            0   
4                                  0  ...                 0            0   
...                              ...  ...               ...          ...   
9737                               0  ...                 0            0   
9738                               0  ...                 0            0   
9739                               0  ...                 0            0   
9740                               0  ...                 0            0   
9741                              

In [22]:
from sklearn.preprocessing import StandardScaler 

In [23]:
scaler = StandardScaler().fit(df_dummy_set)
scaler

StandardScaler()

In [26]:
scaler.transform(df_dummy_set)

array([[-0.01013207, -0.01013207, -0.01013207, ..., -0.09326014,
        -0.02026726, -0.04864667],
       [-0.01013207, -0.01013207, -0.01013207, ..., -0.09326014,
        -0.02026726, -0.04864667],
       [-0.01013207, -0.01013207, -0.01013207, ..., -0.09326014,
        -0.02026726, -0.04864667],
       ...,
       [-0.01013207, -0.01013207, -0.01013207, ..., -0.09326014,
        -0.02026726, -0.04864667],
       [-0.01013207, -0.01013207, -0.01013207, ..., -0.09326014,
        -0.02026726, -0.04864667],
       [-0.01013207, -0.01013207, -0.01013207, ..., -0.09326014,
        -0.02026726, -0.04864667]])

In [27]:
scaler.mean_


array([0.00010265, 0.00010265, 0.00010265, ..., 0.00862246, 0.00041059,
       0.00236091])

In [28]:
scaler.scale_

array([0.01013103, 0.01013103, 0.01013103, ..., 0.092456  , 0.02025894,
       0.04853182])

In [ ]:
from sklearn.cluster import KMeans

In [ ]:
kmeans = Kmeans(2)
